version: "3.9"

services:
  postgres:
    image: postgres:13.22-trixie
    container_name: pdf_postgres
    restart: always
    environment:
      POSTGRES_USER: pdf_user
      POSTGRES_PASSWORD: pdf_secret
      POSTGRES_DB: pdf_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
